### ISSUE TITLE
SIMPLIFY - dry css

### ISSUE THREAD

**Issue by franfranfranfran** [tntburgess/prj-rev-bwfs-dasmoto#1]
https://github.com/tntburgess/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L3
https://github.com/tntburgess/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L12
https://github.com/tntburgess/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L24

try to keep in mind DRY principles when setting your styling. are there any elements on the page that should not receive the helvetica font-family? can we set this styling just once for the entire page?

**Comment by tntburgess** [comment]
Thanks for the feedback!
