### ISSUE TITLE
GREAT - organization / div structure

### ISSUE THREAD

**Issue by franfranfranfran** [tntburgess/prj-rev-bwfs-dasmoto#3]
https://github.com/tntburgess/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L9-L14

great use of divs and class names to keep your code organized and well-structured. consider making use of some well-placed line breaks between the main content sections to increase readability. more info about html styling in general can be found here - https://www.w3schools.com/html/html5_syntax.asp

**Comment by tntburgess** [comment]
Thanks for the feedback!
