### ISSUE TITLE
SUBTLETY - css readability

### ISSUE THREAD

**Issue by franfranfranfran** [tntburgess/prj-rev-bwfs-dasmoto#4]
https://github.com/tntburgess/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L10-L22

i think your code would be a bit clearer if you were to only set the styling that goes to all the h2 elements in the h2 block and then have a separate brushes styling block. what you're doing works but it isn't immediately clear and could lead to confusion later on if you need to change anything or debug.

**Comment by tntburgess** [comment]
Thanks for the feedback!
