### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [tntburgess/prj-rev-bwfs-dasmoto#5]
**GRADE**: Meets Expectations

**SUMMARY**: Excellent job on this project! Other than a little font-family mixup that should be easy to resolve, your site is looking great! Very good job keeping both your project folder and your html / css files neat and organized using proper indentation and divs with class names. 

   Behind the scenes in your css, try to keep an eye out for ways to keep your code DRY. If you have styling being applied to multiple elements, is there a way to avoid setting the styling more than once? Also, consider using html entities when you want special characters on the page. They will ensure that the special characters display correctly across all browsers.

   As a next step try saving your image files locally and then using relative file paths to link to those from your html and css.  The link to css on line 6 of your html is a great example and more info can be found here - http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

Keep up the great work!

**Comment by tntburgess** [comment]
Thanks for the feedback!
